version: '3'
services:

    wp:
        image: atillay/wordpress
        ports:
            - ${WP_PORT}:80
        volumes:
            - .:/var/www:cached

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_HOST=mysql

    maildev:
        image: djfarrelly/maildev
        ports:
            - ${MAILDEV_PORT}:80

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        volumes:
            - ./var/db:/var/lib/mysql
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
